# Generated by Django 4.2.16 on 2025-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miyanMadi', '0002_remove_madimenu_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madimenu',
            name='show_images',
            field=models.BooleanField(default=False, help_text='Toggle whether this menu renders item pictures', verbose_name='Show Images'),
        ),
    ]
