# Generated by Django 4.2.16 on 2025-12-14 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miyanGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BereshtMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(max_length=255, verbose_name='Title (Persian)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('subtitle_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle (Persian)')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('show_images', models.BooleanField(default=True, help_text='Toggle whether this menu renders item pictures', verbose_name='Show Images')),
                ('menu_type', models.CharField(default='main', help_text='Logical type for routing (e.g., main, today, breakfast)', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beresht_menus', to='miyanGroup.branch')),
            ],
            options={
                'verbose_name': 'Beresht Menu',
                'verbose_name_plural': 'Beresht Menus',
                'db_table': 'beresht_menu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereshtMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Section Title (Persian)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Section Title (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='miyanBeresht.bereshtmenu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Beresht Menu Section',
                'verbose_name_plural': 'Beresht Menu Sections',
                'db_table': 'beresht_menu_section',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereshtMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=255, verbose_name='Item Name (Persian)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Item Name (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('price_fa', models.CharField(blank=True, max_length=50, verbose_name='Formatted Price (Persian)')),
                ('price_en', models.CharField(blank=True, max_length=50, verbose_name='Formatted Price (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/%Y/%m/%d/', verbose_name='Item Image')),
                ('video', models.FileField(blank=True, help_text='Animated GIF preview of the item', null=True, upload_to='menu_items/gifs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['gif'])], verbose_name='Item Video (GIF)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='miyanBeresht.bereshtmenusection', verbose_name='Menu Section')),
            ],
            options={
                'verbose_name': 'Beresht Menu Item',
                'verbose_name_plural': 'Beresht Menu Items',
                'db_table': 'beresht_menu_item',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
